### ISSUE TITLE
Error en pagos, la API envía un monto diferente al solicitado.

### ISSUE THREAD

**Issue by kornerita** [payway-ar/sdk-php-ventaonline#14]
https://github.com/decidir/sdk-php-v2/blob/9d260b03c86d5419b52c97a4ce09077727e31476/Decidir/lib/Payment.php#L153

Buenas, es inherente de PHP el error de conversión de double a entero, les dejo un ejemplo de porqué está mal trabajar con valores de punto flotante y después multiplicar por 100 y transformarlo a entero.

```
# php --version
PHP 7.1.18 (cli) (built: May 24 2018 07:59:58) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2018 Zend Technologies
```

```php
var_dump(intval(1238.86*100));
```
Esperado: 

```
int(123886)
```

Obtenido:

```
int(123885)
```

Este es un caso de ejemplo donde falla en un centavo el pago.

Un posible fix puede transformarlo a "string" antes de convertirlo a entero:

```php
var_dump(intval(strval(1238.86*100)));
```
Resultado:

```
int(123886)
```

Saludos,
Federico.

**Comment by joaquin-becerra** [comment]
Exacto!!, ejemplos:

echo intval(19.99*100); // Imprime 1998
echo "\n";
echo intval("19.99"*100); // Imprime 1998
echo "\n";


una solución seria

echo intval(strval("19.99"*100));
echo "\n";


Ademas tampoco se realiza la conversión a entero en los archivos:

https://github.com/decidir/sdk-php-v2/blob/master/Decidir/lib/Cybersource/DigitalGoods.php#L63
https://github.com/decidir/sdk-php-v2/blob/master/Decidir/lib/Cybersource/Retail.php#L76
https://github.com/decidir/sdk-php-v2/blob/master/Decidir/lib/Cybersource/Service.php#L73
https://github.com/decidir/sdk-php-v2/blob/master/Decidir/lib/Cybersource/Ticketing.php#L66

Con lo que en algunos casos si un precio unitario es de "99.99999" se enviá "9999.999' y falla el pago

Por favor es importante corregir estos valores de Cybersource, en nuestro caso los pago fueron rechazados porque se enviaba un valor 99'99.999' en algunos casos, dentro de la info de cybersource

**Comment by nicolaspar** [comment]
Es mejor usar un round:

Solución (https://github.com/decidir/sdk-php-v2/blob/ef5926e8613b8de3f78cc255184e65992f5e4ebc/Decidir/lib/Payment.php#L170):

```
public function rmDecAmount($amount){
    return (int) round(($amount * 100), 0);
}
```

Referencias: 
https://stackoverflow.com/questions/16456615/how-to-convert-float-value-to-integer-in-php
https://floating-point-gui.de/


Lo mejor es que pasaron 4 años de este issue y no lo han solucionado.

**Comment by facundocapua** [comment]
Gracias @nicolaspar por el fix.
Creé un fork con el fix subido por si no quieren cambiar código.

```composer require facundocapua/php-sdk```
